name: Create Release package

on:
  create:
    tags:
      - v*
      
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Build package
        run: |
          cd print-portal
          npm install -g @vue/cli-service
          npm install --production=false
          npm run build --if-present
        env:
          NODE_ENV: production

      - name: Create tar
        run: tar -czf website_${{ env.RELEASE_VERSION }}.tar.gz ./public

      - name: Upload release tar
        uses: actions/upload-artifact@v2
        with:
          name: website_${{ env.RELEASE_VERSION }}
          path: website_${{ env.RELEASE_VERSION }}.tar.gz
